/*DROP TABLE "REVIEW" CASCADE CONSTRAINTS;*/

CREATE TABLE "COMPANY"
(
    COMP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMP_ADDR VARCHAR2(100 BYTE),
    COMP_ADDR_DETAIL VARCHAR2(100 BYTE),
    COMP_NAME VARCHAR2(50),
    BS_REGI_NUM VARCHAR2(20 BYTE) UNIQUE NOT NULL
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE "USER"
(
    USER_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    COMP_ID NUMBER,
    USER_ID VARCHAR2(200 BYTE) NOT NULL,
    USER_NAME VARCHAR2(20 BYTE) NOT NULL,
    USER_PWD VARCHAR2(255 BYTE) NOT NULL,
    EMAIL VARCHAR2(200 BYTE) UNIQUE NOT NULL,
    NICKNAME VARCHAR2(50 BYTE) UNIQUE NOT NULL,
    BIRTH DATE NOT NULL,
    ADDR VARCHAR2(200 BYTE) NOT NULL,
    PHONE CHAR(13 BYTE) NOT NULL,
    GENDER VARCHAR2(10 BYTE) NOT NULL,
    PROFILE_IMG_PATH VARCHAR2(100 BYTE),
    ENROLL_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    STATUS CHAR(1 BYTE) DEFAULT 'T' NOT NULL,
    LAST_LOGIN_AT DATE,
    
        CONSTRAINT FK_COMP_USER
        FOREIGN KEY (COMP_ID)
        REFERENCES "COMPANY" (COMP_ID)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;
  
CREATE TABLE "EVENT_CATEGORY" 
(
    EVENT_CODE CHAR(1 BYTE) PRIMARY KEY,
    EVENT_NAME VARCHAR2(20 BYTE)
) SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE "AUTHORITIES"
(
    AUHTORITY VARCHAR(50 BYTE) PRIMARY KEY,
    USER_NO NUMBER,
    
    CONSTRAINT FK_USER_AUTH
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE "PERSISTENT_LOGINS"
(
    SERIES VARCHAR(64 BYTE) PRIMARY KEY,
    TOKEN VARCHAR(64 BYTE) NOT NULL,
    LAST_USED TIMESTAMP(6) NOT NULL,
    USER_NO NUMBER,
    
    CONSTRAINT FK_USER_PERSIST
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE APP_STATUS(
    STAT_CODE CHAR(1 BYTE) PRIMARY KEY,
    STAT_NAME VARCHAR2(20) NOT NULL
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE "EVENT_APPLICATION"
(
    APP_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NO NUMBER NOT NULL,
    EVENT_CODE CHAR(1 BYTE) NOT NULL,
    STAT_CODE CHAR(1 BYTE) NOT NULL,
    APP_TITLE VARCHAR2(100 BYTE) NOT NULL,
    APP_SUB_TITLE VARCHAR2(100 BYTE) NOT NULL,
    APP_DETAIL CLOB NOT NULL,
    LOCATION VARCHAR2(100 BYTE) NOT NULL,
    LOCATION_DETAIL VARCHAR2(100 BYTE) NOT NULL,
    POST_CODE VARCHAR2(10 BYTE) NOT NULL,
    WEBSITE VARCHAR2(300 BYTE) NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    START_TIME VARCHAR2(100 BYTE) NOT NULL,
    END_TIME VARCHAR2(100 BYTE) NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    SUBMITTED_DATE DATE,
    APPROVED_DATE DATE,
    APP_FEE VARCHAR2(100 BYTE),
    APP_ITEM VARCHAR2(255 BYTE),
    APP_HOST VARCHAR2(100 BYTE),
    APP_ORG VARCHAR2(100 BYTE) NOT NULL,
    APP_SPONSER VARCHAR2(100 BYTE),
    ADMIN_COMMENT CLOB,
    
        CONSTRAINT FK_USER_APP
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO),
            CONSTRAINT FK_ECODE_APP
        FOREIGN KEY (EVENT_CODE)
        REFERENCES "EVENT_CATEGORY" (EVENT_CODE),
            CONSTRAINT FK_STAT_APP
        FOREIGN KEY (STAT_CODE)
        REFERENCES "APP_STATUS" (STAT_CODE)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

/*
ALTER TABLE EVENT_APPLICATION MODIFY (
USER_NO NUMBER NULL,
EVENT_CODE CHAR(1 BYTE) NULL,
STAT_CODE CHAR(1 BYTE) NULL
);
*/

CREATE TABLE "APP_MANAGER"
(
    APP_ID NUMBER PRIMARY KEY,
    MANAGER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL,
    TEL VARCHAR2(20) NOT NULL,
    FAX VARCHAR2(20) NOT NULL,
    
        CONSTRAINT FK_APP_MANAGER
        FOREIGN KEY (APP_ID)
        REFERENCES "EVENT_APPLICATION" (APP_ID)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

DROP TABLE "APP_MANAGER" CASCADE CONSTRAINTS;

CREATE TABLE BOARD_CATEGORY(
    BOARD_CODE CHAR(1 BYTE) PRIMARY KEY,
    BOARD_NAME VARCHAR2(20) NOT NULL
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE IMAGE
(
    IMG_NO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IMG_TYPE CHAR(1) NOT NULL,
    ORIGIN_NAME VARCHAR2(1000) NOT NULL,
    CHANGE_NAME VARCHAR2(1000) NOT NULL,
    IMG_ORDER NUMBER NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    REF_NO NUMBER NOT NULL,
    
        CONSTRAINT FK_IMAGE_CATEGORY
        FOREIGN KEY (IMG_TYPE)
        REFERENCES "BOARD_CATEGORY" (BOARD_CODE)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

/*
ALTER TABLE IMAGE MODIFY (
IMG_TYPE CHAR(1) NULL
);
*/

CREATE TABLE EVENT_PROMOTION
(
    PROM_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    APP_ID NUMBER,
    PROM_TITLE VARCHAR2(100),
    PROM_DETAIL CLOB,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    VIEWS NUMBER DEFAULT 0 NOT NULL,
    
        CONSTRAINT FK_APP_PROM
        FOREIGN KEY (APP_ID)
        REFERENCES "EVENT_APPLICATION" (APP_ID)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE REVIEW
(
        USER_NO NUMBER NOT NULL,
        APP_ID NUMBER NOT NULL,
        "COMMENT" CLOB,
        RATING NUMBER DEFAULT 1 NOT NULL,
        CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
        UPDATE_DATE DATE,
        
        CONSTRAINT PK_REVIEW PRIMARY KEY (USER_NO, APP_ID),
        CONSTRAINT FK_USER_REVIEW
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO),
        CONSTRAINT FK_APP_REVIEW
        FOREIGN KEY (APP_ID)
        REFERENCES "EVENT_APPLICATION" (APP_ID)
    )SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

/*
ALTER TABLE REVIEW DROP CONSTRAINT FK_USER_REVIEW;
ALTER TABLE REVIEW DROP CONSTRAINT FK_APP_REVIEW;
ALTER TABLE REVIEW DROP CONSTRAINT PK_REVIEW;

ALTER TABLE REVIEW MODIFY (
USER_NO NUMBER NULL,
APP_ID NUMBER NULL
);
*/

CREATE TABLE NOTICE
(
    NOTICE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOTICE_TITLE VARCHAR2(100) NOT NULL,
    NOTICE_DETAIL CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    HIGHLIGHT CHAR(1) DEFAULT 'F' NOT NULL
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE QNA
(
    QNA_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    USER_NO NUMBER,
    QNA_TITLE VARCHAR2(100) NOT NULL,
    QNA_DETAIL CLOB NOT NULL,
    CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
    UPDATE_DATE DATE,
    
    CONSTRAINT FK_USER_QNA
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

CREATE TABLE BOOKMARK(

        USER_NO NUMBER NOT NULL,
        APP_ID NUMBER NOT NULL,
        CREATE_DATE DATE DEFAULT SYSDATE NOT NULL,
        
        CONSTRAINT PK_BOOKMARK PRIMARY KEY (USER_NO, APP_ID),
        CONSTRAINT FK_USER_BOOKMARK
        FOREIGN KEY (USER_NO)
        REFERENCES "USER" (USER_NO),
        CONSTRAINT FK_APP_BOOKMARK
        FOREIGN KEY (APP_ID)
        REFERENCES "EVENT_APPLICATION" (APP_ID)
)SEGMENT CREATION IMMEDIATE 
LOGGING
STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
PCTINCREASE 0 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
TABLESPACE FESTA_IT;

/*
ALTER TABLE BOOKMARK DROP CONSTRAINT FK_USER_BOOKMARK;
ALTER TABLE BOOKMARK DROP CONSTRAINT FK_APP_BOOKMARK;
ALTER TABLE BOOKMARK DROP CONSTRAINT PK_BOOKMARK;

ALTER TABLE BOOKMARK MODIFY (
USER_NO NUMBER NULL,
APP_ID NUMBER NULL
);
*/

