ALTER SESSION SET CONTAINER = XEPDB1;


CREATE tablespace festa_it
DATAFILE 'C:\FestaIt\data\festa_it.dbf' size 500m reuse
autoextend on next 100m maxsize unlimited;
CREATE USER FESTA_DB IDENTIFIED BY 1234
DEFAULT TABLESPACE festa_it
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO FESTA_DB;
/*DROP USER FESTADB CASCADE;*/