ALTER SESSION SET CONTAINER = XEPDB1;

CREATE tablespace FESTA_IT
DATAFILE '/opt/oracle/oradata/XE/XEPDB1/FESTAIT.dbf' size 500m reuse
AUTOEXTEND ON NEXT 100m maxsize unlimited
SEGMENT SPACE MANAGEMENT AUTO;

CREATE USER FESTA_DB IDENTIFIED BY 1234
DEFAULT TABLESPACE FESTA_IT
TEMPORARY TABLESPACE temp;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE TO FESTA_DB;

ALTER USER FESTA_DB QUOTA UNLIMITED ON FESTA_IT;